#!/usr/bin/env python3
"""
Synthetic Document Generator - Main Entry Point

This is the main entry point for generating synthetic payment and banking documents.
Run this script to start the interactive CLI.

Usage:
    python generate_docs.py [--config CONFIG_FILE]

Examples:
    # Run with interactive prompts
    python generate_docs.py

    # Run with custom config file
    python generate_docs.py --config my_config.yaml
"""

import sys
import argparse
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / 'src'))

from cli.main import main


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Generate synthetic payment and banking documents for testing.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s
      Run with default configuration and interactive prompts

  %(prog)s --config custom_config.yaml
      Run with custom configuration file

All generated documents include the watermark:
  "This synthetic document is generated by Rahul Raj for testing purpose."

Supported document types:
  - Bank statements
  - Credit card statements
  - Terms & Conditions / Agreements
  - Notifications / Letters
  - Payment / Remittance Advice
  - Emails (.msg)

Supported formats:
  - PDF (.pdf)
  - Microsoft Word (.docx)
  - Microsoft Excel (.xlsx)
  - Outlook Email (.msg)
  - Standard Email (.eml)
  - OpenDocument Text (.odt)
  - Images (.jpeg, .jpg, .png)

For more information, see README.md
        """
    )

    parser.add_argument(
        '--config',
        '-c',
        type=str,
        default='config/default_config.yaml',
        help='Path to configuration file (default: config/default_config.yaml)'
    )

    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()

    # Check if config file exists
    config_path = args.config
    if not Path(config_path).exists():
        # Try default location
        default_path = Path(__file__).parent / 'config' / 'default_config.yaml'
        if default_path.exists():
            config_path = str(default_path)
        else:
            config_path = None

    # Run CLI
    try:
        main(config_path)
    except KeyboardInterrupt:
        print("\n\nOperation cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
