#!/usr/bin/env python3
"""
Basic functionality test for the synthetic document generator.

This script tests that all modules can be imported and basic
document generation works.
"""

import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / 'src'))

print("Testing Synthetic Document Generator\n")
print("=" * 60)

# Test 1: Import all modules
print("\n[Test 1] Importing modules...")
try:
    from utils.watermark import get_watermark_text
    from utils.formatting import format_currency, format_date
    from utils.size_estimator import SizeEstimator
    from data.synthetic import SyntheticDataGenerator
    from data.templates import DocumentTemplates
    from generators import get_generator, GENERATOR_NAMES
    from formats import get_writer, DOCUMENT_FORMAT_SUPPORT
    print("✓ All modules imported successfully")
except Exception as e:
    print(f"✗ Import failed: {e}")
    sys.exit(1)

# Test 2: Verify watermark
print("\n[Test 2] Testing watermark...")
try:
    watermark = get_watermark_text()
    expected = "This synthetic document is generated by Rahul Raj for testing purpose."
    assert watermark == expected, f"Watermark mismatch: {watermark}"
    print(f"✓ Watermark verified: '{watermark}'")
except Exception as e:
    print(f"✗ Watermark test failed: {e}")
    sys.exit(1)

# Test 3: Test data generator
print("\n[Test 3] Testing synthetic data generation...")
try:
    data_gen = SyntheticDataGenerator(seed=42)
    person = data_gen.generate_person()
    assert 'full_name' in person
    assert 'email' in person
    print(f"✓ Generated person: {person['full_name']}")

    address = data_gen.generate_address()
    assert 'city' in address
    assert 'state' in address
    print(f"✓ Generated address: {address['city']}, {address['state']}")

    merchant = data_gen.generate_merchant()
    assert 'name' in merchant
    print(f"✓ Generated merchant: {merchant['name']}")
except Exception as e:
    print(f"✗ Data generation test failed: {e}")
    sys.exit(1)

# Test 4: Test document generators
print("\n[Test 4] Testing document generators...")
try:
    for doc_type in ['bank_statement', 'credit_card_statement', 'notification']:
        generator = get_generator(doc_type, seed=42)
        content = generator.generate_content()
        assert content is not None
        assert isinstance(content, dict)
        print(f"✓ Generated {GENERATOR_NAMES[doc_type]} content")
except Exception as e:
    print(f"✗ Document generator test failed: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Test 5: Test format writers (just instantiation)
print("\n[Test 5] Testing format writers...")
try:
    test_file = Path("test_output.pdf")
    writer = get_writer(str(test_file))
    assert writer is not None
    print("✓ PDF writer instantiated")

    test_file = Path("test_output.docx")
    writer = get_writer(str(test_file))
    assert writer is not None
    print("✓ DOCX writer instantiated")

    test_file = Path("test_output.xlsx")
    writer = get_writer(str(test_file))
    assert writer is not None
    print("✓ XLSX writer instantiated")
except Exception as e:
    print(f"✗ Format writer test failed: {e}")
    sys.exit(1)

# Test 6: End-to-end test (generate one document)
print("\n[Test 6] End-to-end test: Generating a sample PDF...")
try:
    output_dir = Path("./test_output")
    output_dir.mkdir(exist_ok=True)

    # Generate bank statement
    generator = get_generator('bank_statement', seed=42)
    content = generator.generate_content()

    # Write to PDF
    filepath = output_dir / "test_bank_statement.pdf"
    writer = get_writer(str(filepath))
    writer.write(content, 'bank_statement')

    assert filepath.exists()
    file_size = filepath.stat().st_size
    print(f"✓ Generated PDF: {filepath} ({file_size} bytes)")

    # Generate credit card statement XLSX
    generator = get_generator('credit_card_statement', seed=42)
    content = generator.generate_content()

    filepath = output_dir / "test_credit_card.xlsx"
    writer = get_writer(str(filepath))
    writer.write(content, 'credit_card_statement')

    assert filepath.exists()
    file_size = filepath.stat().st_size
    print(f"✓ Generated XLSX: {filepath} ({file_size} bytes)")

    # Generate email
    generator = get_generator('email', seed=42)
    content = generator.generate_content()

    filepath = output_dir / "test_email.eml"
    writer = get_writer(str(filepath))
    writer.write(content, 'email')

    assert filepath.exists()
    file_size = filepath.stat().st_size
    print(f"✓ Generated EML: {filepath} ({file_size} bytes)")

except Exception as e:
    print(f"✗ End-to-end test failed: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Summary
print("\n" + "=" * 60)
print("✓ All tests passed!")
print(f"\nTest output saved to: {output_dir.absolute()}")
print("\nYou can now run the full CLI with:")
print("  python generate_docs.py")
print("\n" + "=" * 60)
