"""
CLI prompts and user interaction utilities.

This module handles all user interactions for the document generator CLI.
"""

from typing import List, Dict, Tuple, Optional
from rich.console import Console
from rich.prompt import Prompt, Confirm, IntPrompt
from rich.table import Table
from rich.panel import Panel
from rich import print as rprint

from src.generators import GENERATOR_NAMES
from src.formats import DOCUMENT_FORMAT_SUPPORT


console = Console()


class DocumentGeneratorPrompts:
    """
    Handles all CLI prompts for the document generator.
    """

    @staticmethod
    def show_welcome():
        """Display welcome message."""
        panel = Panel(
            "[bold blue]Synthetic Document Generator[/bold blue]\n\n"
            "Generate realistic payment and banking documents for testing.\n"
            "[yellow]All documents include mandatory watermark: "
            "'This synthetic document is generated by Rahul Raj for testing purpose.'[/yellow]",
            title="Welcome",
            border_style="blue"
        )
        console.print(panel)
        console.print()

    @staticmethod
    def select_document_types() -> List[str]:
        """
        Prompt user to select document types.

        Returns:
            list: Selected document type keys
        """
        console.print("[bold cyan]Step 1: Select Document Types[/bold cyan]\n")

        # Display options table
        table = Table(show_header=True, header_style="bold magenta")
        table.add_column("Option", style="cyan", width=8)
        table.add_column("Document Type", style="green")

        options = list(GENERATOR_NAMES.items())
        for i, (key, name) in enumerate(options, start=1):
            table.add_row(str(i), name)

        table.add_row("[bold]A[/bold]", "[bold]All document types[/bold]")

        console.print(table)
        console.print()

        while True:
            selection = Prompt.ask(
                "[yellow]Enter your selection[/yellow] (e.g., 1,3,5 or A for all)",
                default="A"
            )

            if selection.upper() == 'A':
                return list(GENERATOR_NAMES.keys())

            try:
                # Parse comma-separated numbers
                indices = [int(x.strip()) for x in selection.split(',')]
                selected = []

                for idx in indices:
                    if 1 <= idx <= len(options):
                        selected.append(options[idx - 1][0])
                    else:
                        console.print(f"[red]Invalid option: {idx}[/red]")
                        raise ValueError()

                if selected:
                    return selected
                else:
                    console.print("[red]Please select at least one document type.[/red]")

            except ValueError:
                console.print("[red]Invalid input. Please enter numbers separated by commas (e.g., 1,3,5) or 'A' for all.[/red]")

    @staticmethod
    def select_formats(doc_type: str) -> List[str]:
        """
        Prompt user to select formats for a document type.

        Args:
            doc_type: Document type key

        Returns:
            list: Selected format extensions
        """
        doc_name = GENERATOR_NAMES[doc_type]
        supported_formats = DOCUMENT_FORMAT_SUPPORT.get(doc_type, [])

        if not supported_formats:
            return []

        console.print(f"\n[bold cyan]Formats for: {doc_name}[/bold cyan]\n")

        # Display format options
        table = Table(show_header=True, header_style="bold magenta")
        table.add_column("Option", style="cyan", width=8)
        table.add_column("Format", style="green")

        for i, fmt in enumerate(supported_formats, start=1):
            table.add_row(str(i), f".{fmt.upper()}")

        table.add_row("[bold]A[/bold]", "[bold]All supported formats[/bold]")

        console.print(table)
        console.print()

        while True:
            selection = Prompt.ask(
                "[yellow]Select formats[/yellow] (e.g., 1,2 or A for all)",
                default="A"
            )

            if selection.upper() == 'A':
                return supported_formats

            try:
                indices = [int(x.strip()) for x in selection.split(',')]
                selected = []

                for idx in indices:
                    if 1 <= idx <= len(supported_formats):
                        selected.append(supported_formats[idx - 1])
                    else:
                        console.print(f"[red]Invalid option: {idx}[/red]")
                        raise ValueError()

                if selected:
                    return selected
                else:
                    console.print("[red]Please select at least one format.[/red]")

            except ValueError:
                console.print("[red]Invalid input. Please enter numbers separated by commas or 'A'.[/red]")

    @staticmethod
    def configure_output() -> Dict[str, str]:
        """
        Configure output settings.

        Returns:
            dict: Output configuration
        """
        console.print("\n[bold cyan]Step 3: Output Configuration[/bold cyan]\n")

        output_dir = Prompt.ask(
            "[yellow]Output directory[/yellow]",
            default="./output"
        )

        return {
            'directory': output_dir,
        }

    @staticmethod
    def configure_generation() -> Dict[str, any]:
        """
        Configure generation settings (count vs size).

        Returns:
            dict: Generation configuration
        """
        console.print("\n[bold cyan]Step 4: Generation Configuration[/bold cyan]\n")

        console.print("Choose generation mode:")
        console.print("  [cyan]1.[/cyan] Generate a specific number of documents")
        console.print("  [cyan]2.[/cyan] Generate until approximate total size is reached")
        console.print()

        while True:
            mode = Prompt.ask(
                "[yellow]Select mode[/yellow]",
                choices=["1", "2"],
                default="1"
            )

            if mode == "1":
                count = IntPrompt.ask(
                    "[yellow]Number of documents per type/format combination[/yellow]",
                    default=5
                )
                return {
                    'mode': 'count',
                    'count': count,
                }

            elif mode == "2":
                size_str = Prompt.ask(
                    "[yellow]Target total size[/yellow] (e.g., 10MB, 50MB, 1GB)",
                    default="10MB"
                )
                return {
                    'mode': 'size',
                    'target_size': size_str,
                }

    @staticmethod
    def show_summary(config: Dict) -> bool:
        """
        Display configuration summary and ask for confirmation.

        Args:
            config: Complete configuration

        Returns:
            bool: True if user confirms, False otherwise
        """
        console.print("\n[bold cyan]Configuration Summary[/bold cyan]\n")

        # Document types
        console.print("[bold]Document Types:[/bold]")
        for doc_type in config['selected_types']:
            doc_name = GENERATOR_NAMES[doc_type]
            formats = ', '.join(f".{f}" for f in config['formats'][doc_type])
            console.print(f"  • {doc_name}: {formats}")

        console.print()

        # Output
        console.print(f"[bold]Output Directory:[/bold] {config['output']['directory']}")

        # Generation settings
        if config['generation']['mode'] == 'count':
            console.print(f"[bold]Documents per type/format:[/bold] {config['generation']['count']}")
        else:
            console.print(f"[bold]Target total size:[/bold] {config['generation']['target_size']}")

        console.print()

        # Estimate total files
        total_combinations = sum(len(config['formats'][dt]) for dt in config['selected_types'])
        if config['generation']['mode'] == 'count':
            total_files = total_combinations * config['generation']['count']
            console.print(f"[bold yellow]Estimated total files: {total_files}[/bold yellow]")
        else:
            console.print(f"[bold yellow]Files will be generated until target size is reached[/bold yellow]")

        console.print()

        return Confirm.ask("[bold green]Proceed with generation?[/bold green]", default=True)

    @staticmethod
    def show_progress_header():
        """Display progress header."""
        console.print("\n[bold cyan]Generating Documents...[/bold cyan]\n")

    @staticmethod
    def show_completion_summary(stats: Dict):
        """
        Display completion summary.

        Args:
            stats: Generation statistics
        """
        console.print("\n[bold green]✓ Generation Complete![/bold green]\n")

        # Stats table
        table = Table(show_header=False, box=None)
        table.add_column("Metric", style="cyan")
        table.add_column("Value", style="green bold")

        table.add_row("Total files generated:", str(stats.get('total_files', 0)))
        table.add_row("Total size:", stats.get('total_size_str', 'Unknown'))
        table.add_row("Output directory:", stats.get('output_dir', ''))

        if 'duration' in stats:
            table.add_row("Duration:", f"{stats['duration']:.2f} seconds")

        console.print(table)
        console.print()

        # Breakdown by type
        if 'by_type' in stats:
            console.print("[bold]Files by type:[/bold]")
            for doc_type, count in stats['by_type'].items():
                doc_name = GENERATOR_NAMES.get(doc_type, doc_type)
                console.print(f"  • {doc_name}: {count}")

        console.print()

    @staticmethod
    def show_error(message: str):
        """
        Display error message.

        Args:
            message: Error message
        """
        console.print(f"\n[bold red]Error: {message}[/bold red]\n")

    @staticmethod
    def show_warning(message: str):
        """
        Display warning message.

        Args:
            message: Warning message
        """
        console.print(f"[yellow]Warning: {message}[/yellow]")
