"""
Watermark utilities for synthetic documents.

This module provides the mandatory watermark text and helper functions
to ensure it's applied consistently across all document formats.
"""

# The official watermark text - MUST be used in all generated documents
WATERMARK_TEXT = "This synthetic document is generated by Rahul Raj for testing purpose."


def get_watermark_text() -> str:
    """
    Get the standard watermark text.

    Returns:
        str: The watermark text to be included in all documents
    """
    return WATERMARK_TEXT


def get_watermark_banner(width: int = 80, char: str = "=") -> str:
    """
    Get a formatted watermark banner for text-based documents.

    Args:
        width: Width of the banner in characters
        char: Character to use for the border

    Returns:
        str: Formatted watermark banner with borders
    """
    border = char * width
    text = WATERMARK_TEXT
    padding = (width - len(text)) // 2

    return f"{border}\n{' ' * padding}{text}\n{border}"


def get_watermark_html() -> str:
    """
    Get HTML-formatted watermark for email bodies or HTML documents.

    Returns:
        str: HTML formatted watermark
    """
    return f"""
    <div style="background-color: #fff3cd; border: 2px solid #856404; padding: 10px;
                margin-bottom: 20px; text-align: center; font-weight: bold;
                color: #856404; font-family: Arial, sans-serif;">
        {WATERMARK_TEXT}
    </div>
    """


def get_watermark_plain_centered(width: int = 80) -> str:
    """
    Get centered watermark text without borders.

    Args:
        width: Width for centering

    Returns:
        str: Centered watermark text
    """
    padding = (width - len(WATERMARK_TEXT)) // 2
    return f"{' ' * padding}{WATERMARK_TEXT}"
